services:
  backend:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:passwordpo@db:5432/sentiment
    volumes:
      - .:/app
<<<<<<< HEAD
    restart: always
=======
    restart: always
>>>>>>> 066196c (adding unit testing for api-controllers and all of them are PASSED)
